name: Test CodeToCloud workshop using Bats

on: push

jobs:
  pester-test:
    name: Bats core test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup BATS testing framework
        uses: mig4/setup-bats@v1.2.0
        with:
          bats-version: 1.3.0

      - name: Replace tokens
        uses: cschleiden/replace-tokens@121d9153eda2951d490e9f724a67ff095ab4c4f7
        with:
          tokenPrefix: __
          tokenSuffix: __
          files: Tests/InputSetupScript.txt
        env:
          ghtoken: ${{secrets.GHTOKEN}}
          azdotoken: ${{secrets.AZDOTOKEN}}

      - name: Display the path
        run: cat Tests/InputSetupScript.txt
        shell: bash
          
      - name: Test
        run: bats Tests/UnitTests.sh.sh