name: "Find docker tags"
on:
  schedule:
  - cron: "* 7 * * *"

jobs:
  check_docker_versions_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check_docker_tags
        id: dockertags
        run: |
          currentversion="1.3.0"
          dockertagsurl="https://mcr.microsoft.com/v2/vscode/devcontainers/universal/tags/list"

          allversions=`curl -s -L $dockertagsurl`
          linuxversions=`echo "$allversions"| jq -r '.tags[] | select(test("^[0-9].*linux"))'` # skip latest

          higherversionfound=false
          higherversions=""

          for linuxversion in $linuxversions
          do
            strippedLinuxVersion=`echo "$linuxversion" | cut -d'-' -f 1`
            if [ "$(printf '%s\n' "$currentversion" "$strippedLinuxVersion" | sort -V | head -n1)" = "$currentversion" ] && [ "$currentversion" != "$strippedLinuxVersion" ]; then 
                echo "${strippedLinuxVersion} greater than ${currentversion}"
                higherversionfound=true
                higherversions+=${strippedLinuxVersion},
            fi
          done

          echo ${higherversionfound}
          echo ${higherversions}
          echo "::set-output name=higherversionfound::${higherversionfound}"
          echo "::set-output name=higherversions::${higherversions}"

      - name: Retrieve parameters
        run: |
          higestversionfound=${{ steps.dockertags.outputs.higestversionfound }}
          higherversions=${{ steps.dockertags.outputs.higherversions }}
      - name: Slack Notification
        if: ${{ steps.dockertags.outputs.higherversionfound == 'true' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: New docker tags have been found for the Linux devcontainer; ${{ steps.dockertags.outputs.higherversions }}

